/**:
  ros__parameters:
    gravity_alignment:
        heading_lidar: [1.0, 0.0, 0.0]

    preprocess:
      lidar_type: 2               # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
      scan_line: 16
      scan_rate: 10               # only need to be set for velodyne, unit: Hz,
      timestamp_unit: 2           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 0.3
      blind_for_human_pilot: 1.6  # This parameter is to reject cloud points from human pilots

    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.003
      b_gyr_cov: 0.001
      fov_degree: 360.0
      det_range: 100.0
      extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic,

      # extrinsic_T: [ 0.0494615,  0.10735763, -0.07427067 ]
      # extrinsic_R: [ -4.3653500000e-03, -9.9999000000e-01, -5.4567700000e-04,
      #                 2.3024800000e-04, 5.4467700000e-04, -1.0000000000e+00,
      #                 9.9999000000e-01, -4.3654700000e-03, 2.2786900000e-04  ]

      # From acl_jackal2
      extrinsic_T: [ 0.07025405, -0.10158666, -0.04942693 ]
      extrinsic_R: [-2.9046527369e-02, -9.9957706196e-01, -1.7154151723e-03,
                    -6.9278006858e-02, 3.7251435690e-03, -9.9759064383e-01,
                    9.9717458733e-01, -2.8857692625e-02, -6.9356874944e-02  ]


    filter_size_map: 0.3

    publish:
      path_en: true
      scan_publish_en: true        # false: close all the point cloud output
      dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
      scan_lidarframe_pub_en: true # true: output the point cloud scans in the LiDAR frame
      scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body frame
      scan_baseframe_pub_en: true  # true: output the point cloud scans in the base frame

    pcd_save:
      pcd_save_en: false
      interval: -1                 # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

    verbose: false
    point_filter_num_for_preprocessing: 1 # If it is set to `1`, full point cloud gonna be publlished
    point_filter_num: 4                   # For pose estimation.
    max_iteration: 4
    cube_side_length: 1000.0
